# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "8e72081fdb833e699b901d79864fca91"
name = "Cin7SerialProducts"
application_url = "https://shopify-cin7-serial-number-pos.vercel.app"
embedded = false

[build]
automatically_update_urls_on_dev = false

[webhooks]
api_version = "2026-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_assigned_fulfillment_orders,read_customers,read_fulfillments,read_locations,read_merchant_managed_fulfillment_orders,read_orders,read_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://shopify.dev/apps/default-app-home/api/auth",
  "https://shopify-cin7-serial-number-pos.vercel.app/auth/callback",
  "https://shopify-cin7-serial-number-pos.vercel.app/auth/shopify/callback",
  "https://shopify-cin7-serial-number-pos.vercel.app/api/auth/callback"
]

[pos]
embedded = true
